{% set name = "memoized-property" %}
{% set version = "1.0.3" %}
{% set sha256 = "4be4d0209944b9b9b678dae9d7e312249fe2e6fb8bdc9bdaa1da4de324f0fcf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - memoized_property

about:
  home: https://github.com/estebistec/python-memoized-property
  license: BSD-3
  summary: 'A simple python decorator for defining properties that only run their fget function once'
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - npavlovikj
